# Primeros pasos - numpy

## Creando arreglos

In [18]:
import numpy as np

In [19]:
arreglo = np.array([1,2,3,4,5])

In [20]:
type(arreglo)

numpy.ndarray

In [22]:
lista = [1,2,3,4,5]

In [23]:
lista_nueva = list()
for item in lista:
    lista_nueva.append(item + 2)

In [24]:
lista_nueva

[3, 4, 5, 6, 7]

In [21]:
arreglo + 2

array([3, 4, 5, 6, 7])

In [25]:
arreglo

array([1, 2, 3, 4, 5])

In [26]:
arreglo_para_suma = np.array([2,5,3,1,4])

In [27]:
arreglo + arreglo_para_suma

array([3, 7, 6, 5, 9])

In [ ]:
a = np.arange(15).reshape(3, 5)

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
a.dtype.name

In [ ]:
a.size

## Magic word de tiempo

In [28]:
%%time 
print("hola")

hola
Wall time: 0 ns


In [57]:
%%timeit -n 100 -r 50 
lista_nueva = list()
for item in lista:
    lista_nueva.append(item + 2)

617 ns ± 5.41 ns per loop (mean ± std. dev. of 50 runs, 100 loops each)


In [76]:
%%timeit -n 100 -r 50 
arreglo + 2

1.28 µs ± 167 ns per loop (mean ± std. dev. of 50 runs, 100 loops each)


In [13]:
%%timeit -n 10 -r 5 
print("hola")

hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
61 µs ± 34 µs per loop (mean ± std. dev. of 5 runs, 10 loops each)


In [37]:
lista = list(range(1,10000000))

In [38]:
len(lista_nueva)

9999999

In [39]:
import numpy as np
arreglo_numpy = np.array(range(1,10000000))

In [40]:
len(arreglo_numpy)

9999999

In [41]:
%%timeit -n 1 -r 1
lista_nueva = list()
for item in lista:
    lista_nueva.append(item + 2)

1.26 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [42]:
%%timeit -n 1 -r 1 
arreglo_numpy + 2

20.7 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [29]:
arreglo_notas1 = np.array([8,6,7,8,6]) 
arreglo_notas2 = np.array([4,10,9,5,7]) 

In [36]:
print("promedio 1 ", np.mean(arreglo_notas1))
print("promedio 2 ", np.mean(arreglo_notas2))

promedio 1  7.0
promedio 2  7.0


In [31]:
np.var(arreglo_notas1)

0.8

In [32]:
np.var(arreglo_notas2)

5.2

In [34]:
np.std(arreglo_notas1)

0.8944271909999159

In [35]:
np.std(arreglo_notas2)

2.280350850198276